### PR TITLE
hi hello yes hungarian translation

### PR DESCRIPTION
**Pull request by Righted1**
made with love

### CODE REVIEW

**Comment by MegamiShin** [comment]
is it made with love tho?

**Comment by Righted1** [comment]
Oh yes boy, it is!

**Comment by MegamiShin** [comment]
are you sure????

**Comment by Righted1** [comment]
yes i am sure.

**Comment by nodomw** [comment]
Jesus christ do you even speak Hungarian? You just put all of the strings into DeepL and translated them one-by-one.

**Comment by MegamiShin** [comment]
deepl good but how dare u not make translations with love 👎🏻

**Comment by nodomw** [comment]
i make translations with passion

**Comment by okeeeeeee** [comment]
> Jesus christ do you even speak Hungarian? You just put all of the strings into DeepL and translated them one-by-one.

istenen 🥶

**Comment by Righted1** [comment]
> Jesus christ do you even speak Hungarian? You just put all of the strings into DeepL and translated them one-by-one.

perzse beszélek én magyarul

**Comment by ccreaper** [comment]
Already used Hungarian translation. Feel free to push any fixes necessary.

**Pull request closed without merging**
