### PR TITLE
Hungarian Translation

### PR DESCRIPTION
**Pull request by okeeeeeee**
written at 3am and rushed somewhat, will come back later to read over and change any mistakes

### CODE REVIEW

**Comment by eleven-teen** [comment]
newgen translator

**Comment by okeeeeeee** [comment]
> newgen translator

geci

**Comment by Righted1** [comment]
> newgen translator

kurva faság

**Comment by ccreaper** [comment]
Already used Hungarian translation. Feel free to push any fixes necessary.

**Pull request closed without merging**
